"""init

Revision ID: 1
Revises: 
Create Date: 2019-11-30 17:49:26.814371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "foundations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("payment_address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_foundations_id"), "foundations", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=True)
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("private_key", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_methods_id"), "payment_methods", ["id"], unique=False
    )
    op.create_table(
        "user_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_tokens_id"), "user_tokens", ["id"], unique=False)
    op.create_table(
        "payment_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_method_id", sa.Integer(), nullable=True),
        sa.Column("foundation_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18), nullable=True),
        sa.ForeignKeyConstraint(["foundation_id"], ["foundations.id"],),
        sa.ForeignKeyConstraint(["payment_method_id"], ["payment_methods.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payment_rules_id"), "payment_rules", ["id"], unique=False)
    op.create_table(
        "payment_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_rule_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["payment_rule_id"], ["payment_rules.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_history_id"), "payment_history", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_history_id"), table_name="payment_history")
    op.drop_table("payment_history")
    op.drop_index(op.f("ix_payment_rules_id"), table_name="payment_rules")
    op.drop_table("payment_rules")
    op.drop_index(op.f("ix_user_tokens_id"), table_name="user_tokens")
    op.drop_table("user_tokens")
    op.drop_index(op.f("ix_payment_methods_id"), table_name="payment_methods")
    op.drop_table("payment_methods")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_foundations_id"), table_name="foundations")
    op.drop_table("foundations")
    # ### end Alembic commands ###
